insert INTO EXCHANGE (ORIGIN_CURRENCY, DESTINY_CURRENCY, EXCHANGE_RATE) values('PEN', 'USD', 3.74);
insert INTO EXCHANGE (ORIGIN_CURRENCY, DESTINY_CURRENCY, EXCHANGE_RATE) values('USD', 'PEN', 0.27);
insert INTO EXCHANGE (ORIGIN_CURRENCY, DESTINY_CURRENCY, EXCHANGE_RATE) values('PEN', 'CLP', 0.0040);
insert INTO EXCHANGE (ORIGIN_CURRENCY, DESTINY_CURRENCY, EXCHANGE_RATE) values('CLP', 'PEN', 252.59);